apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: k8s-web
  name: k8s-web
spec:
  ports:
  - name: 8080-8080
    port: 8080
    protocol: TCP
    targetPort: 8080
  selector:
    app: k8s-web
  type: LoadBalancer
status:
  loadBalancer: {}
