apiVersion: v1
kind: Service
metadata:
  creationTimestamp: null
  labels:
    app: k8s-name
  name: k8s-name
spec:
  ports:
  - name: 7070-7070
    port: 7070
    protocol: TCP
    targetPort: 7070
  selector:
    app: k8s-name
  type: ClusterIP
status:
  loadBalancer: {}
